"""add unit_purchace_cost to Product

Revision ID: 1939c75335ba
Revises: 7ffa78c08521
Create Date: 2025-07-31 19:50:57.561652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1939c75335ba'
down_revision: Union[str, None] = '7ffa78c08521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('unit_purchase_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'unit_purchase_cost')
    # ### end Alembic commands ###
