"""add ignore to order

Revision ID: 581a2c439846
Revises: 81abff1b2dde
Create Date: 2025-08-16 13:22:56.338895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581a2c439846'
down_revision: Union[str, None] = '81abff1b2dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ignore', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_order_created_not_ignored', 'order', ['created_at'], unique=False, postgresql_where=sa.text('ignore = false'))
    op.create_index(op.f('ix_order_ignore'), 'order', ['ignore'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_ignore'), table_name='order')
    op.drop_index('ix_order_created_not_ignored', table_name='order', postgresql_where=sa.text('ignore = false'))
    op.drop_column('order', 'ignore')
    # ### end Alembic commands ###
