"""edit Offer model v2

Revision ID: 9739b77b28c0
Revises: 636d15788aeb
Create Date: 2025-07-31 23:41:28.418772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9739b77b28c0'
down_revision: Union[str, None] = '636d15788aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'ean',
               existing_type=sa.VARCHAR(length=13),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'ean',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###
