"""add taxrate

Revision ID: ad870f4ef86b
Revises: f26467ee7290
Create Date: 2025-08-12 17:22:43.983436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad870f4ef86b'
down_revision: Union[str, None] = 'f26467ee7290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('23'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'tax_rate')
    # ### end Alembic commands ###
