"""add origin_id to Offer

Revision ID: f26467ee7290
Revises: 9739b77b28c0
Create Date: 2025-08-01 17:10:51.895147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f26467ee7290'
down_revision: Union[str, None] = '9739b77b28c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('origin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('offer_external_id_marketplace_id_key', 'offer', type_='unique')
    op.create_unique_constraint(None, 'offer', ['external_id', 'origin_id', 'marketplace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='unique')
    op.create_unique_constraint('offer_external_id_marketplace_id_key', 'offer', ['external_id', 'marketplace_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('offer', 'origin_id')
    # ### end Alembic commands ###
